#***************************
# LOCALHOST
#***************************

### Get all cars
GET http://localhost:3000/cars

### Get car by id
GET http://localhost:3000/cars/63df3547c2a426f406c4de09


### Create car
POST http://localhost:3000/cars HTTP/1.1
content-type: application/json

{
  "make": "Lexus",
  "model": "RX350",
  "year": "2023",
  "color": "Black",
  "displacement": "3.5 L",
  "horsepower": "270 @ 6,200 rpm",
  "engineType": "Gas",
  "transmission": "5-speed automatic",
  "drivetrain": "All wheel"
}


### PUT contact (Update)
PUT http://localhost:3000/cars/63df3539c2a426f406c4de08 HTTP/1.1
content-type: application/json

{
  "make": "Lexus",
  "model": "RX350",
  "year": "2009",
  "color": "Black",
  "displacement": "3.5 L",
  "horsepower": "270 @ 6,200 rpm",
  "engineType": "Gas",
  "transmission": "5-speed automatic",
  "drivetrain": "All wheel"
}

### DELETE contact
DELETE http://localhost:3000/cars/63df486b2a999d24bc6c41f2 HTTP/1.1


#***************************
# PRODUCTION Deploy
#***************************

### Get all cars
GET https://abhathaway-cse341-techspec.onrender.com/cars


### Get car by id
GET https://abhathaway-cse341-techspec.onrender.com/cars/63df3539c2a426f406c4de08


### Create car
POST https://abhathaway-cse341-techspec.onrender.com/cars HTTP/1.1
content-type: application/json

{
   "make": "Lexus",
   "model": "RX350",
   "year": "2023",
   "color": "Black",
   "displacement": "3.5 L",
   "horsepower": "270 @ 6,200 rpm",
   "engineType": "Gas",
   "transmission": "5-speed automatic",
   "drivetrain": "All wheel"
}


### PUT contact
PUT https://abhathaway-cse341-techspec.onrender.com/cars/63df3539c2a426f406c4de08 HTTP/1.1
content-type: application/json

{
  "make": "Lexus",
  "model": "RX350",
  "year": "2009",
  "color": "White",
  "displacement": "3.5 L",
  "horsepower": "270 @ 6,200 rpm",
  "engineType": "Gas",
  "transmission": "5-speed automatic",
  "drivetrain": "All wheel"
}


### DELETE contact
DELETE https://abhathaway-cse341-techspec.onrender.com/cars/63df489cccb62061fc273317 HTTP/1.1